server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/quizzes/**
        - id: game-session-service
          uri: lb://game-session-service
          predicates:
            - Path=/api/game-sessions/**
  config:
    import:
      - "shared-config.yml"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

