server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://root:pass@localhost:27017/quiz-db?authSource=admin
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: file:.secrets/public.pem


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

