server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://root:pass@localhost:27017/quiz-db?authSource=admin
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka