services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"  #AMQP
      - "15672:15672" #UI
      - "61613:61613" #STOMP
    command: > 
      bash -c "
        rabbitmq-plugins enable --offline rabbitmq_management &&
        rabbitmq-plugins enable --offline rabbitmq_stomp &&
        rabbitmq-server
      "

volumes:
  mongo:

networks:
  microservices:
    driver: bridge