spring:
  application:
    name: game-session-service
  config:
    import: optional:configserver:http://localhost:8888


logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          socket:
            messaging: DEBUG
        cloud: DEBUG
      hibernate: WARN
