spring:
  application:
    name: config-server

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/Shared/OneDrive/Proyectos/kahootclone/config-repo

server:
  port: 8888